### ISSUE TITLE
gzip报错

### ISSUE THREAD

**Issue by wby238** [maxujie/xuetang-down#3]
下载的课程：
http://www.xuetangx.com/courses/course-v1:TsinghuaX+10421094X_2015_2+sp/info

错误代码：
> F:\Mooc\xuetang-down\src>python xuetang-down.py
课前引言
Traceback (most recent call last):
  File "xuetang-down.py", line 157, in <module>
    main()
  File "xuetang-down.py", line 154, in main
    xtdown.download_all_subtitles()
  File "xuetang-down.py", line 138, in download_all_subtitles
    self.download_subtitle(subsection)
  File "xuetang-down.py", line 129, in download_subtitle
    unzipped_data = gzip_decompress(content)
  File "xuetang-down.py", line 147, in gzip_decompress
    unzipped_data = f.read()
  File "C:\Program Files\Python35\lib\gzip.py", line 274, in read
    return self._buffer.read(size)
  File "C:\Program Files\Python35\lib\gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "C:\Program Files\Python35\lib\gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\xef\xbb')

顺便问一下还有什么能用的mooc下载工具吗，github上的都挂得差不多了……

**Comment by maxujie** [comment]
@wby238 用你的课程试了一下，并没有报错 😶

**Comment by wby238** [comment]
我再次试了一下，一样报错，你原来的课程倒是正常，但没有下载字幕文件，只是渲染在cmd里……
再换了一个课程，结果中途gzip错误……

> F:\Mooc\xuetang-down-master\src>python xuetang-down.py
0.1 Piazza讨论区
0.2 在线实验平台
1.1 课程概述
Traceback (most recent call last):
  File "xuetang-down.py", line 157, in <module>
    main()
  File "xuetang-down.py", line 154, in main
    xtdown.download_all_subtitles()
  File "xuetang-down.py", line 138, in download_all_subtitles
    self.download_subtitle(subsection)
  File "xuetang-down.py", line 129, in download_subtitle
    unzipped_data = gzip_decompress(content)
  File "xuetang-down.py", line 147, in gzip_decompress
    unzipped_data = f.read()
  File "C:\Program Files\Python35\lib\gzip.py", line 274, in read
    return self._buffer.read(size)
  File "C:\Program Files\Python35\lib\gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "C:\Program Files\Python35\lib\gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\xef\xbb')
